### ISSUE TITLE
Fonts packaging

### ISSUE THREAD

**Issue by ratijas** [yuanbohan/rs-figlet#2] opened 2019-08-13 10:06 UTC
Using this as an external crate panics on `FIGfont::standard()` because font file is not available at given relative path "resources/standard.flf". Consider packaging font(-s) via `include_str!` macro or by any other suitable means.

**Comment by yuanbohan** [comment] 2020-03-22 15:19
I am very sorry for the late reply, I will update it ASAP

**Comment by yuanbohan** [comment] 2020-03-22 17:00
@ratijas hi ratijas, I don't know if `figlet-rs` is still useful to you,  the issue is already fixed in `0.1.3`. I will close the issue.

**Closed as completed by yuanbohan** 2020-03-22 17:00 UTC

**Comment by ratijas** [comment] 2020-03-23 14:29
hi, @yuanbohan.  thank you, that's awesome!  gonna use it right now as a part of cli frontend for a [morse-coder ](https://github.com/ratijas/windows-rust-counters) university project!
